# Generated by Django 3.2.16 on 2025-02-12 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20250212_0319'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date', 'author')},
        ),
    ]
